[package]
name = "cli"
edition = "2021"
version.workspace = true

[lib]
doctest = false

[dependencies.anyhow]
workspace = true

[dependencies.clap]
workspace = true

[dependencies.service]
workspace = true
