[package]
name = "cli"
edition = "2021"
version.workspace = true

[dependencies.anyhow]
workspace = true

[dependencies.clap]
version = "4.5.8"
features = ["derive"]

[dependencies.service]
workspace = true
