[package]
name = "phoneme"
edition = "2021"

[dependencies.anyhow]
workspace = true

[dependencies.once_cell]
workspace = true

[dependencies.thiserror]
version = "1.0.61"

[dependencies.tracing]
workspace = true

[dev-dependencies.pretty_assertions]
version = "1.4.0"
