[package]
name = "phoneme"
edition = "2021"

[dependencies.anyhow]
workspace = true

[dependencies.once_cell]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.tracing]
workspace = true

[dev-dependencies.pretty_assertions]
workspace = true
