[package]
name = "service"
edition = "2021"

[lib]
doctest = false

[dependencies.anyhow]
workspace = true

[dependencies.domain]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.tracing]
workspace = true
