[package]
name = "service"
edition = "2021"

[dependencies.anyhow]
workspace = true

[dependencies.domain]
path = "../domain"

[dependencies.serde]
version = "1.0.203"
features = ["derive"]

[dependencies.thiserror]
version = "1.0.61"
